site_name: hsp90-smfret-model
site_description: "Documentation for a simple alignment tool for DNA sequences."
site_author: "Abhinav Mishra"
site_url: https://bibymaths.github.io/hsp90-smfret-model
use_directory_urls: false
repo_url: https://github.com/bibymaths/hsp90-smfret-model
repo_name: bibymaths/hsp90-smfret-model

theme:
  name: material
  language: en
  font:
    text: Ubuntu           # The font for standard paragraph text
    code: Fira Code        # The font for code blocks
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo # Change this to your brand color!
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - toc.integrate

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: numpy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_files:
  - images/logo.png
  - images/flow.png
  - images/structure.png

nav:
  - Home: index.md
  - Overview: overview.md
  - Mathematical Model: math.md
  - Usage: usage.md
  - API Reference: api.md
  - Contributing: contributing.md

copyright: >
  Copyright &copy; 2025 <a href="https://bibymaths.github.io">Abhinav Mishra</a>.